[init.hyper]
train_df_file = "../lung/result/GDC_lung_tissue/split80/all_beta_normalized.csv"
dmp_files = "../lung/champ_result/GDC_lung_tissue/merged_result.csv"
majority_out_path = "../lung/result/GDC_lung_tissue/split80"

[feature_selection.hyper]
validate_df_file = "../lung/result/GDC_lung_tissue/split20/all_beta_normalized.csv"
train_out_path = "../lung/result/GDC_lung_tissue/split80/section_3/sfs"
validate_out_path = "../lung/result/GDC_lung_tissue/split20/section_3/sfs"
dbeta_info_file = "../lung/result/GDC_lung_tissue/split80/section_5/dbeta_TSS_0.29_consensus.csv"
training_param_file = "../lung/training_param.json"

[GO_distance_matrix.hyper]
input_file = "lung/result/GDC_lung_tissue/split80/section_2/dbeta_TSS_0.29.csv"
base_out_dir = "lung/result/GDC_lung_tissue/split80/GO_distance_matrix"

[clustering_visual.hyper]
result_prefix = "dbeta_TSS_0.29"
dbeta_file = "../lung/result/GDC_lung_tissue/split80/section_2/dbeta_TSS_0.29.csv"
bp_file = "../lung/result/GDC_lung_tissue/split80/GO_distance_matrix/distance_matrix_bp.csv"
cc_file = "../lung/result/GDC_lung_tissue/split80/GO_distance_matrix/distance_matrix_cc.csv"
mf_file = "../lung/result/GDC_lung_tissue/split80/GO_distance_matrix/distance_matrix_mf.csv"
terms_count_file = "../lung/result/GDC_lung_tissue/split80/GO_distance_matrix/terms_count.csv"
result_out_path = "../lung/result/GDC_lung_tissue/split80/section_5"

[simple_model.hyper]
dbeta_file = "../lung/result/GDC_lung_tissue/split80/section_5/dbeta_TSS_0.29_consensus.csv"
selected_feature_file = "../lung/result/GDC_lung_tissue/split20/section_3/rfe/selected_features.json"
train_out_path = "../lung/result/GSE235414/split80/section_6"
validate_out_path = "../lung/result/GSE235414/split20/section_6"
df_file1 = "../lung/champ_result/GDC_lung_tissue/all_beta_normalized_TCGA_LUAD_LUSC.csv"
df_file2 = "../lung/champ_result/GSE235414/all_beta_normalized_GSE235414.csv"
training_param_file = "../lung/training_param.json"

[preprocess.filtering]
threshold = 0.29

[preprocess.dbeta]
dmp_before_dropna_shape_feature = 138396
dmp_after_dropna_shape_feature = 100570
NaN_dbeta_feature = []
delta_beta_avg_feature_num = 353507
delta_beta_avg_feature_num_remove_NaN = 353507
delta_beta_avg_feature_num_remove_NaN_join_dmp = 353507

[preprocess.filtering.hyper]
avg_dbeta_lower_bound = 300
avg_dbeta_upper_bound = 500
