[init.hyper]
beta_file_number = 2
test_ratio = 0.2
splitting_seed = 42
normal_number_0 = 37
normal_number_1 = 37
data_source = "GDC_lung_tissue"
is_columns_duplicated = 2

[preprocess.filtering]
threshold = 0.31

[preprocess.merge_and_split]
feature_size_0 = 120677
feature_size_1 = 360242
feature_size_intersection = 115119
Before_dropna_dfn_shape = [ 115119, 74,]
Before_dropna_dfc_shape = [ 115119, 844,]
After_dropna_dfn_shape = [ 115119, 74,]
After_dropna_dfc_shape = [ 115119, 677,]
training_set_samples = 1086
testing_set_samples = 151
training_class_distribution = [ 543, 543,]
testing_class_distribution = [ 17, 134,]
Before_SMOTE_X_train_shape = [ 600, 115119,]
Before_SMOTE_y_train_shape = 600
After_SMOTE_X_train_shape = [ 1086, 115119,]
After_SMOTE_y_train_shape = 1086

[preprocess.dbeta]
dmp_before_dropna_shape_feature = 289650
dmp_after_dropna_shape_feature = 219382
delta_beta_avg = 115119
NaN_dbeta_feature = []
delta_beta_avg_remove_NaN = 115119
delta_beta_avg_remove_NaN_with_gene_name = 115119

[clustering.hyper]
dbeta_file = "dbeta_TSS_0.31"
gene_set_file = "selected_feature_names_set"
bp_file = "distance_matrix_bp"
cc_file = "distance_matrix_cc"
mf_file = "distance_matrix_mf"
terms_count_file = "terms_count"

[combination.hyper]
dbeta_file = "dbeta_TSS_0.31_consensus"

[machine_learning.Decision_Tree]
max_features = 10
min_samples_leaf = 70
min_samples_split = 70

[machine_learning.Random_Forest]
max_features = 5
min_samples_leaf = 80
min_samples_split = 80
n_estimators = 100

[machine_learning.SVM]
C = 50
kernel = "rbf"

[machine_learning.XGBoost]
colsample_bytree = 0.6
learning_rate = 0.1
max_depth = 2
min_child_weight = 40
n_estimators = 50
subsample = 0.7

[preprocess.filtering.hyper]
avg_dbeta_lower_bound = 300
avg_dbeta_upper_bound = 500
