[init.hyper]
train_df_file = "../prostate/champ_result/GSE269244_80/all_beta_normalized.csv"
dmp_files = "../prostate/champ_result/GSE269244/DMP_result_TN.csv"
majority_out_path = "../prostate/result/GSE269244/split80"

[feature_selection.hyper]
validate_df_file = "../prostate/champ_result/GSE269244_20/all_beta_normalized.csv"
train_out_path = "../prostate/result/GSE269244/split80/section_3/rfe"
validate_out_path = "../prostate/result/GSE269244/split20/section_3/rfe"
dbeta_info_file = "../prostate/result/GSE269244/split80/section_5/dbeta_TSS_0.21_consensus.csv"
training_param_file = "../prostate/training_param.json"

[GO_distance_matrix.hyper]
input_file = "prostate/result/GSE269244/split80/section_2/dbeta_TSS_0.21.csv"
base_out_dir = "prostate/result/GSE269244/split80/GO_distance_matrix"

[clustering_visual.hyper]
result_prefix = "dbeta_TSS_0.21"
dbeta_file = "../prostate/result/GSE269244/split80/section_2/dbeta_TSS_0.21.csv"
bp_file = "../prostate/result/GSE269244/split80/GO_distance_matrix/distance_matrix_bp.csv"
cc_file = "../prostate/result/GSE269244/split80/GO_distance_matrix/distance_matrix_cc.csv"
mf_file = "../prostate/result/GSE269244/split80/GO_distance_matrix/distance_matrix_mf.csv"
terms_count_file = "../prostate/result/GSE269244/split80/GO_distance_matrix/terms_count.csv"
result_out_path = "../prostate/result/GSE269244/split80/section_5"

[simple_model.hyper]
dbeta_file = "../prostate/result/GSE269244/split80/section_5/dbeta_TSS_0.21_consensus.csv"
selected_feature_file = "../prostate/result/GSE269244/split20/section_3/rfe/selected_features.json"
train_out_path = "../prostate/result/GSE269244/split80/section_6"
validate_out_path = "../prostate/result/GSE269244/split20/section_6"
df_file = "../prostate/champ_result/GSE269244/all_beta_normalized.csv"
training_param_file = "../prostate/training_param.json"

[preprocess.filtering]
threshold = 0.21

[preprocess.dbeta]
dmp_before_dropna_shape_feature = 188706
dmp_after_dropna_shape_feature = 136630
NaN_dbeta_feature = []
delta_beta_avg_feature_num = 695602
delta_beta_avg_feature_num_remove_NaN = 695602
delta_beta_avg_feature_num_remove_NaN_join_dmp = 695602

[preprocess.filtering.hyper]
avg_dbeta_lower_bound = 300
avg_dbeta_upper_bound = 500
