[init.hyper]
beta_file_number = 2
test_ratio = 0.2
splitting_seed = 42
normal_number_0 = 2
normal_number_1 = 84
data_source = "GDC_stomach_GSE99553"
is_columns_duplicated = 2
is_columns_duplicated_1 = 1

[preprocess.merge_and_split]
feature_size_0 = 375937
feature_size_1 = 411036
feature_size_intersection = 375382
Before_dropna_dfn_shape = [ 375382, 86,]
Before_dropna_dfc_shape = [ 375382, 395,]
After_dropna_dfn_shape = [ 375382, 86,]
After_dropna_dfc_shape = [ 375382, 395,]
training_set_samples = 632
testing_set_samples = 158
training_class_distribution = [ 308, 324,]
testing_class_distribution = [ 87, 71,]
Before_SMOTE_X_shape = [ 481, 375382,]
Before_SMOTE_y_shape = 481
After_SMOTE_X_shape = [ 790, 375382,]
After_SMOTE_y_shape = 790
